development:
  clients:
    default:
      database: capstone_work2_development
      hosts:
        - <%= ENV['MONGO_HOST'] ||="localhost:27017"%>
      options:
  options:

test:
  clients:
    default:
      database: capstone_work2_test
      hosts:
        - <%= ENV['MONGO_HOST'] ||="localhost:27017" %>
      options:
        read:
          mode: :primary
        max_pool_size: 1

production:
    clients:
        default:
            uri: <%= ENV['MLAB_URI']%>
            options:
                connect_timeout: 15
